In [30]:
import pandas as pd
df= pd.read_csv("homeprices(nominal).csv")
df= df.drop('Unnamed: 3',axis='columns')
df=df.dropna(how='all')
df

          town     area     price
0    kukatpally  2600.0  550000.0
1    kukatpally  3000.0  565000.0
2    kukatpally  3200.0  610000.0
3    kukatpally  3600.0  680000.0
4    kukatpally  4000.0  725000.0
5      gandipet  2600.0  585000.0
6      gandipet  2800.0  615000.0
7      gandipet  3300.0  650000.0
8      gandipet  3600.0  710000.0
9   lingampally  2600.0  575000.0
10  lingampally  2900.0  600000.0
11  lingampally  3100.0  620000.0
12  lingampally  3600.0  695000.0

In [31]:
pd.get_dummies(df['town '] )

    gandipet  kukatpally  lingampally
0      False        True        False
1      False        True        False
2      False        True        False
3      False        True        False
4      False        True        False
5       True       False        False
6       True       False        False
7       True       False        False
8       True       False        False
9      False       False         True
10     False       False         True
11     False       False         True
12     False       False         True

In [32]:
print(df.columns)

Index(['town ', 'area', 'price'], dtype='object')

In [33]:
dummies=pd.get_dummies(df['town '] ).astype(int)
dummies

    gandipet  kukatpally  lingampally
0          0           1            0
1          0           1            0
2          0           1            0
3          0           1            0
4          0           1            0
5          1           0            0
6          1           0            0
7          1           0            0
8          1           0            0
9          0           0            1
10         0           0            1
11         0           0            1
12         0           0            1

In [34]:
merged= pd.concat([df,dummies], axis='columns')
merged

          town     area     price  gandipet  kukatpally  lingampally
0    kukatpally  2600.0  550000.0         0           1            0
1    kukatpally  3000.0  565000.0         0           1            0
2    kukatpally  3200.0  610000.0         0           1            0
3    kukatpally  3600.0  680000.0         0           1            0
4    kukatpally  4000.0  725000.0         0           1            0
5      gandipet  2600.0  585000.0         1           0            0
6      gandipet  2800.0  615000.0         1           0            0
7      gandipet  3300.0  650000.0         1           0            0
8      gandipet  3600.0  710000.0         1           0            0
9   lingampally  2600.0  575000.0         0           0            1
10  lingampally  2900.0  600000.0         0           0            1
11  lingampally  3100.0  620000.0         0           0            1
12  lingampally  3600.0  695000.0         0           0            1

In [35]:
final= merged.drop(['town ','lingampally'],axis='columns')
final

      area     price  gandipet  kukatpally
0   2600.0  550000.0         0           1
1   3000.0  565000.0         0           1
2   3200.0  610000.0         0           1
3   3600.0  680000.0         0           1
4   4000.0  725000.0         0           1
5   2600.0  585000.0         1           0
6   2800.0  615000.0         1           0
7   3300.0  650000.0         1           0
8   3600.0  710000.0         1           0
9   2600.0  575000.0         0           0
10  2900.0  600000.0         0           0
11  3100.0  620000.0         0           0
12  3600.0  695000.0         0           0

In [36]:
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [40]:
x= final.drop('price', axis='columns')
x

      area  gandipet  kukatpally
0   2600.0         0           1
1   3000.0         0           1
2   3200.0         0           1
3   3600.0         0           1
4   4000.0         0           1
5   2600.0         1           0
6   2800.0         1           0
7   3300.0         1           0
8   3600.0         1           0
9   2600.0         0           0
10  2900.0         0           0
11  3100.0         0           0
12  3600.0         0           0

In [42]:
y= final.price
y

0     550000.0
1     565000.0
2     610000.0
3     680000.0
4     725000.0
5     585000.0
6     615000.0
7     650000.0
8     710000.0
9     575000.0
10    600000.0
11    620000.0
12    695000.0
Name: price, dtype: float64

In [43]:
model.fit(x,y)

LinearRegression()

In [45]:
model.predict([[2800,0,1]])

C:\Users\Dell\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([565089.22812299])

In [46]:
#to predict the dropped column use 0 0
model.predict([[3000,0,0]])

C:\Users\Dell\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([616155.12792948])

In [47]:
#to know how accurate ur model is?
#.score compares the predicted values to labels
model.score(x,y)

0.9573929037221872

In [86]:
#using hot one encoder
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
le=LabelEncoder()

In [87]:
dfle['town '] = le.fit_transform(dfle['town '])

In [88]:
X = dfle[['town ', 'area']].values  # 2D array with two columns
Y = dfle['price'].values

In [89]:
ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(drop='first'), [0])  # drop='first' avoids dummy variable trap
    ],
    remainder='passthrough'  # keep 'area' as is
)

In [90]:
X = ct.fit_transform(X)

In [91]:
# Fit linear regression model
model = LinearRegression()
model.fit(X, Y)

LinearRegression()

In [92]:
prediction = model.predict([[0, 0, 3000]])
print(prediction)

[630482.69189422]